name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create and Push Tag
        run: |
          VERSION=$(cat VERSION | tr -d ' \n\r')

          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists, skipping."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git tag -a "$VERSION" -m "$VERSION"
            git push origin "$VERSION"
          fi